CC/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from CC import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^demographics/', include('demographics.urls', namespace='demographics')),
    url(r'^drug_allergies/', include('drug_allergies.urls', namespace='drug_allergies')),
    url(r'^family_history/', include('family_history.urls', namespace='family_history')),
    url(r'^file_upload/', include('file_upload.urls', namespace='file_upload')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^medical_history/', include('medical_history.urls', namespace='medical_history')),
    url(r'^medications/', include('medications.urls', namespace='medications')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^surgical_history/', include('surgical_history.urls', namespace='surgical_history')),
    url(r'^symptom_tracker/', include('symptom_tracker.urls', namespace='symptom_tracker')),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/account/profile/')),
    url(r'^login/$', login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'account/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'account/reset_password.html',
    'post_reset_redirect': 'account:password_reset_done', 'email_template_name': 'account/reset_password_email.html'},
    name='reset_password'),


    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'account/password_reset_done.html'},
    name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
    {'template_name': 'account/reset_password_confirm.html', 'post_reset_redirect':
    'account:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
        name='password_reset_complete'),


]

demographics/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.DemoView.as_view(), name='demographics'),
    url(r'^form/$', views.DemoCreate.as_view(), name='create_demographics'),
    url(r'edit/(?P<pk>\d+)/$', views.DemoUpdateView.as_view(), name='demo_update'),

]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^solutions/$', views.solutions, name='solutions'),
    url(r'^FAQ/$', views.FAQ, name='FAQ'),
    url(r'^about_us/$', views.about_us, name='about_us'),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    #email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = (
            'username',
            #'first_name',
            #'last_name',
            #'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        #user.first_name = self.cleaned_data['first_name']
       # user.last_name = self.cleaned_data['last_name']
       # user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name'
            )

account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.shortcuts import render, redirect
from account.forms import (
    RegistrationForm,
    EditProfileForm
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash





def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/account')
        else:
            return render(request, 'account/reg_form.html',
                          {'form': form})
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'account/reg_form.html', args)

def profile(request):
    args = {'user': request.user}
    return render(request, 'account/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'account/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'account/change_password.html', args)

account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}"/>
    <!--<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" /> -->
    <script src="{% static 'accounts/bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'accounts/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block head %}
    <title>Login</title>
    {% endblock %}
</head>

<body>

<nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'home:home' %}"class="navbar-brand">CloudChart</a>

            </div>

            <!-- menu items -->

            <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="{% url 'demographics:demographics' %}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span> Demo
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home:solutions' %}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span> Solutions
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home:about_us' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> About Us
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home:FAQ' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> FAQ
                        </a>
                    </li>
                    <li class="active">
                        <a href="/account/logout">
                        <span class="glyphicon glyphicon-off"  aria-hidden="true"></span> Logout
                        </a>
                    </li>

                </ul>

                {% else %}
                 <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="{% url 'home:solutions' %}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span> Solutions
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home:about_us' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> About Us
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'home:FAQ' %}">
                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> FAQ
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'account:register' %}">
                        <span class="glyphicon glyphicon-off" href="/account/register" aria-hidden="true"></span> SignUp
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'account:login' %}">
                        <span class="glyphicon glyphicon-off"  aria-hidden="true"></span> Login
                        </a>
                    </li>
                 </ul>
                    {% endif %}



            </div>
        </div>
    </nav>
    {% block body %}
        <h1>Base</h1>
    {% endblock %}
</body>
</html>