CC/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from CC import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^demographics/', include('demographics.urls', namespace='demographics')),
    url(r'^drug_allergies/', include('drug_allergies.urls', namespace='drug_allergies')),
    url(r'^family_history/', include('family_history.urls', namespace='family_history')),
    url(r'^file_upload/', include('file_upload.urls', namespace='file_upload')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^medical_history/', include('medical_history.urls', namespace='medical_history')),
    url(r'^medications/', include('medications.urls', namespace='medications')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^surgical_history/', include('surgical_history.urls', namespace='surgical_history')),
    url(r'^symptom_tracker/', include('symptom_tracker.urls', namespace='symptom_tracker')),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demographics/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.DemoView.as_view(), name='demographics'),
    url(r'^form/$', views.DemoCreate.as_view(), name='create_demographics'),
    url(r'edit/(?P<pk>\d+)/$', views.DemoUpdateView.as_view(), name='demo_update'),

]

demographics/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

'''
Observation:
    the django.contrib.auth.User model is a foreign key to the Demographics
    model. The User model has it's own first_name and last_name fields. As
    such if we were to have them repeated here, that leads to redundancy
    and possibly conflicting data. For example if the user has the first and
    last names in the User field and they differ from what we have here, 
    which one is the right one?

    The solution, delete the first_name and last_name fields

    Oh perhaps is this supposed to be the 'User' recording data about other people?
    In which case this model would be correct.
'''

class Demographics(models.Model):
     first_name = models.CharField(max_length=50, null=True)
     middle_name = models.CharField(max_length=50, null=True)
     last_name = models.CharField(max_length=50, null=True)
     prefix = models.CharField(max_length=50, null=True)
     user = models.ForeignKey(User, null=True)
     
     def __str__(self):
          return self.user.first_name + ' - ' + self.middle_name 

     def get_absolute_url(self):
          return reverse('demographics:demographics')

demographics/forms.py
from django import forms
from .models import Demographics
from django.contrib.auth.forms import UserChangeForm


class DemographicsForm(forms.ModelForm):
    class Meta:
        model = Demographics
        fields = ('first_name', 'last_name', 'middle_name')


class DemoEditForm(forms.ModelForm):
    class Meta:
        model = Demographics
        fields = ('first_name', 'last_name')

demographics/views.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render
from demographics.forms import DemographicsForm
from demographics.models import Demographics



class DemoView(TemplateView):
    template_name = 'demographics/demographics.html'

    def get(self, request):
        form = DemographicsForm()

        # if you want to display on the demographics objects
        # belonging to a specific user, this is done by adding a filter
        #
        demos = Demographics.objects.filter(user = request.user)

        context = {
            'demos': demos, 'form': form
        }

        return render(request, self.template_name, context)


class DemoCreate(CreateView):
    model = Demographics
    fields = ['first_name', 'middle_name','last_name']

    def form_valid(self, form):
        '''
        How to create a form and add the user instance as a foreign key is
        described at 
        https://docs.djangoproject.com/en/1.11/topics/class-based-views/generic-editing/#models-and-request-user
        '''
        form.instance.user = self.request.user
        return super(DemoCreate, self).form_valid(form)


class DemoUpdateView(UpdateView):
    model = Demographics
    fields = ['first_name', 'middle_name','last_name']

    def get_queryset(self):
        qs = super(DemoUpdateView, self).get_queryset()

        return qs.filter(user=self.request.user)

demographics/templates/demographics/demoform_form.html
{% extends 'base.html' %}

{% block body %}
<h1>demo bucky@!</h1>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'demographics/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-0">
            <button type="submit" class="btn btn-success">Submit</button>

        </div>
    </div>

</form>

{% endblock %}

demographics/templates/demographics/demographics.html
{% extends 'base.html' %}

{% block body %}
<h1>demo display from database!</h1>


    {% if demos %}

    {% for demographics in demos  %}
       <p><strong> First Name</strong> {{ demographics.first_name }}</p>
        {{ demographics.middle_name }}
        {{ demographics.last_name }}



    

    {% endfor %}

    <div><a href="{% url 'demographics:demo_update' user.id %}">Edit demographics</a></div>
    
    {% else %}
    <h3>you dont have demo yet</h3>
    <div><a href="{% url 'demographics:create_demographics' %}">Create demographics</a></div>

    {% endif %}


{% endblock %}

demographics/templates/demographics/demographics_edit.html
{% extends 'base.html' %}

{% block body %}
<h1>edit demographics</h1>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'demographics/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-0">
            <button type="submit" class="btn btn-success">Submit</button>

        </div>
    </div>

</form>

{% endblock %}

demographics/templates/demographics/demographics_form.html
{% extends 'base.html' %}

{% block body %}
<h1>demographics</h1>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'demographics/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-0">
            <button type="submit" class="btn btn-success">Submit</button>

        </div>
    </div>

</form>

{% endblock %}

demographics/templates/demographics/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>

        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

</div>
{% endfor %}